/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuCategory = IDL.Variant({
  'momos' : IDL.Null,
  'coldDrinks' : IDL.Null,
  'burgers' : IDL.Null,
  'pizza' : IDL.Null,
  'rolls' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : MenuCategory,
  'priceInr' : IDL.Nat,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getMenuItemsByCategory' : IDL.Func(
      [MenuCategory],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'initializeMenuItems' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuCategory = IDL.Variant({
    'momos' : IDL.Null,
    'coldDrinks' : IDL.Null,
    'burgers' : IDL.Null,
    'pizza' : IDL.Null,
    'rolls' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : MenuCategory,
    'priceInr' : IDL.Nat,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getMenuItemsByCategory' : IDL.Func(
        [MenuCategory],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'initializeMenuItems' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };